Fix import error by building without visibility=hidden
On Fedora 27, importing the mididings module fails with:

   ImportError: dynamic module does not define init function (init_mididings)

Removing '-fvisibility=hidden' from the compiler options fixes
this.